all:
  vars:
    ansible_user: bob
    ansible_python_interpreter: /usr/bin/python3

  hosts:
    pmx-fr-gbe-prod-01:
      ansible_host: 192.168.0.27
    vm-monitor-01:
      ansible_host: 10.35.30.10
    ct-backup-01:
      ansible_host: 10.35.40.10
    ct-bastion-01:
      ansible_host: 10.35.10.14
    vm-proxy-01:
      ansible_host: 10.35.10.10
    vm-app-01:
      ansible_host: 10.35.20.10

  children:
    bastion:
      hosts:
        ct-bastion-01:

    docker:
      hosts:
        vm-app-01:
        vm-proxy-01:

    proxy:
      hosts:
        vm-proxy-01:

    apps:
      hosts:
        vm-app-01:

    backup:
      hosts:
        ct-backup-01:

    monitoring:
      hosts:
        vm-monitor-01:

    node_exporters:
      hosts:
        vm-proxy-01:
        vm-app-01:
        ct-backup-01:

    proxmox:
      hosts:
         pmx-fr-gbe-prod-01:


