---
- name: Install iptables persistence
  ansible.builtin.apt:
    name:
      - iptables-persistent
    state: present
    update_cache: true
    
- name: Ensure /etc/iptables exists
  ansible.builtin.file:
    path: /etc/iptables
    state: directory
    owner: root
    group: root
    mode: "0755"
    
- name: Deploy global IPv4 forwarding config
  copy:
    dest: /etc/sysctl.d/99-forward.conf
    content: |
      net.ipv4.ip_forward=1
    mode: "0644"

- name: Apply sysctl
  command: sysctl --system

- name: Deploy iptables rules
  ansible.builtin.template:
    src: iptables.rules.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: "0644"

- name: Reload networking
  command: ifreload -a

- name: Restore iptables rules
  ansible.builtin.shell: iptables-restore < /etc/iptables/rules.v4
  args:
    executable: /bin/bash
